const FLOW_STATUS = {
    BOOKING_CREATED: "BOOKING_CREATED",
    DRIVER_SEARCHING: "DRIVER_SEARCHING",
    DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
    DRIVER_CONFIRMED: "DRIVER_CONFIRMED",
    DRIVER_EN_ROUTE: "DRIVER_EN_ROUTE",
    DRIVER_ARRIVED: "DRIVER_ARRIVED",
    TRIP_STARTED: "TRIP_STARTED",
    TRIP_COMPLETED: "TRIP_COMPLETED",
    FARE_CALCULATED: "FARE_CALCULATED",
    PAYMENT_PENDING: "PAYMENT_PENDING",
    PAYMENT_PROCESSING: "PAYMENT_PROCESSING",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
    COMPLETED: "COMPLETED",
    CUSTOMER_CANCELLED: "CUSTOMER_CANCELLED",
    DRIVER_CANCELLED: "DRIVER_CANCELLED",
    DRIVER_UNAVAILABLE: "DRIVER_UNAVAILABLE",
    DRIVER_REASSIGNING: "DRIVER_REASSIGNING",
    DRIVER_REASSIGNED: "DRIVER_REASSIGNED",
    DRIVER_REASSIGNMENT_FAILED: "DRIVER_REASSIGNMENT_FAILED",
    DRIVER_NO_SHOW: "DRIVER_NO_SHOW",
    NO_SHOW: "NO_SHOW",
    SYSTEM_CANCELLED: "SYSTEM_CANCELLED"
};

const EDGES = [
    [FLOW_STATUS.BOOKING_CREATED, [FLOW_STATUS.DRIVER_SEARCHING]],
    [FLOW_STATUS.DRIVER_SEARCHING, [
        FLOW_STATUS.DRIVER_ASSIGNED,
        FLOW_STATUS.DRIVER_CONFIRMED,
        FLOW_STATUS.CUSTOMER_CANCELLED,
        FLOW_STATUS.SYSTEM_CANCELLED
    ]],
    [FLOW_STATUS.DRIVER_ASSIGNED, [
        FLOW_STATUS.DRIVER_CONFIRMED,
        FLOW_STATUS.CUSTOMER_CANCELLED,
        FLOW_STATUS.DRIVER_CANCELLED,
        FLOW_STATUS.DRIVER_UNAVAILABLE,
        FLOW_STATUS.DRIVER_REASSIGNING,
        FLOW_STATUS.SYSTEM_CANCELLED
    ]],
    [FLOW_STATUS.DRIVER_CONFIRMED, [
        FLOW_STATUS.DRIVER_EN_ROUTE,
        FLOW_STATUS.DRIVER_ARRIVED,
        FLOW_STATUS.TRIP_STARTED,
        FLOW_STATUS.CUSTOMER_CANCELLED,
        FLOW_STATUS.DRIVER_CANCELLED,
        FLOW_STATUS.DRIVER_UNAVAILABLE,
        FLOW_STATUS.DRIVER_NO_SHOW,
        FLOW_STATUS.DRIVER_REASSIGNING,
        FLOW_STATUS.SYSTEM_CANCELLED
    ]],
    [FLOW_STATUS.DRIVER_EN_ROUTE, [
        FLOW_STATUS.DRIVER_ARRIVED,
        FLOW_STATUS.TRIP_STARTED,
        FLOW_STATUS.DRIVER_UNAVAILABLE,
        FLOW_STATUS.DRIVER_CANCELLED,
        FLOW_STATUS.CUSTOMER_CANCELLED,
        FLOW_STATUS.DRIVER_NO_SHOW,
        FLOW_STATUS.SYSTEM_CANCELLED
    ]],
    [FLOW_STATUS.DRIVER_ARRIVED, [
        FLOW_STATUS.TRIP_STARTED,
        FLOW_STATUS.NO_SHOW,
        FLOW_STATUS.CUSTOMER_CANCELLED,
        FLOW_STATUS.DRIVER_UNAVAILABLE
    ]],
    [FLOW_STATUS.TRIP_STARTED, [FLOW_STATUS.TRIP_COMPLETED]],
    [FLOW_STATUS.TRIP_COMPLETED, [FLOW_STATUS.FARE_CALCULATED, FLOW_STATUS.PAYMENT_PENDING]],
    [FLOW_STATUS.FARE_CALCULATED, [FLOW_STATUS.PAYMENT_PENDING, FLOW_STATUS.COMPLETED]],
    [FLOW_STATUS.PAYMENT_PENDING, [FLOW_STATUS.PAYMENT_PROCESSING, FLOW_STATUS.PAYMENT_FAILED, FLOW_STATUS.COMPLETED]],
    [FLOW_STATUS.PAYMENT_PROCESSING, [FLOW_STATUS.PAYMENT_SUCCESS, FLOW_STATUS.PAYMENT_FAILED]],
    [FLOW_STATUS.PAYMENT_FAILED, [FLOW_STATUS.PAYMENT_PENDING, FLOW_STATUS.PAYMENT_PROCESSING]],
    [FLOW_STATUS.PAYMENT_SUCCESS, [FLOW_STATUS.COMPLETED]],
    [FLOW_STATUS.DRIVER_UNAVAILABLE, [FLOW_STATUS.DRIVER_REASSIGNING, FLOW_STATUS.DRIVER_CANCELLED, FLOW_STATUS.SYSTEM_CANCELLED]],
    [FLOW_STATUS.DRIVER_REASSIGNING, [
        FLOW_STATUS.DRIVER_REASSIGNED,
        FLOW_STATUS.DRIVER_REASSIGNMENT_FAILED,
        FLOW_STATUS.DRIVER_CONFIRMED,
        FLOW_STATUS.CUSTOMER_CANCELLED,
        FLOW_STATUS.SYSTEM_CANCELLED
    ]],
    [FLOW_STATUS.DRIVER_REASSIGNED, [
        FLOW_STATUS.DRIVER_CONFIRMED,
        FLOW_STATUS.DRIVER_EN_ROUTE,
        FLOW_STATUS.DRIVER_ARRIVED,
        FLOW_STATUS.TRIP_STARTED
    ]],
    [FLOW_STATUS.DRIVER_REASSIGNMENT_FAILED, [FLOW_STATUS.SYSTEM_CANCELLED]],
    [FLOW_STATUS.DRIVER_NO_SHOW, [FLOW_STATUS.DRIVER_REASSIGNING, FLOW_STATUS.SYSTEM_CANCELLED]],
    [FLOW_STATUS.NO_SHOW, [FLOW_STATUS.PAYMENT_PENDING, FLOW_STATUS.COMPLETED]],
    [FLOW_STATUS.CUSTOMER_CANCELLED, []],
    [FLOW_STATUS.DRIVER_CANCELLED, []],
    [FLOW_STATUS.SYSTEM_CANCELLED, []],
    [FLOW_STATUS.COMPLETED, []]
];

const TRANSITIONS = {};
for (const [from, tos] of EDGES) {
    TRANSITIONS[from] = tos;
}

const assertValidTransition = (from, to) => {
    if (!from || !to) {
        const err = new Error("Missing booking status");
        err.code = "INVALID_BOOKING_STATUS";
        throw err;
    }
    if (from === to) return true;
    const allowed = TRANSITIONS[from] || [];
    if (allowed.includes(to)) return true;
    const err = new Error(`Invalid booking status transition: ${from} -> ${to}`);
    err.code = "INVALID_BOOKING_STATUS";
    throw err;
};

const resolveFlowStatus = (booking) => {
    if (booking.flowStatus) return booking.flowStatus;
    switch (booking.bookingStatus) {
        case "PENDING":
        case "Searching":
            return FLOW_STATUS.DRIVER_SEARCHING;
        case "CONFIRMED":
            return FLOW_STATUS.DRIVER_CONFIRMED;
        case "ONGOING":
            return FLOW_STATUS.TRIP_STARTED;
        case "Completed":
            return FLOW_STATUS.FARE_CALCULATED;
        case "Cancelled":
            return FLOW_STATUS.CUSTOMER_CANCELLED;
        case "NO_DRIVER_AVAILABLE":
            return FLOW_STATUS.SYSTEM_CANCELLED;
        default:
            return FLOW_STATUS.DRIVER_SEARCHING;
    }
};

const applyFlowStatus = (booking, to, by = "system") => {
    const from = resolveFlowStatus(booking);
    assertValidTransition(from, to);
    if (from === to) {
        return { from, to, by, changed: false };
    }
    booking.flowStatus = to;
    booking.flowStatusHistory = booking.flowStatusHistory || [];
    booking.flowStatusHistory.push({ status: to, at: new Date(), by });
    return { from, to, by, changed: true };
};

module.exports = {
    FLOW_STATUS,
    TRANSITIONS,
    assertValidTransition,
    applyFlowStatus,
    resolveFlowStatus
};